colocados = ("Atlético-MG", "Flamengo", "Palmeiras", "Red-Bull-Bragantino", "Corinthians", "Fortalez", "Internacional", "Fluminense", "América-MG", "Ceará")
print("-="*20)
print(f"os dez primeiros colocados do brasileirão são: {colocados}")
print("-="*20)
print(f"os cinco primeiros colocados são {colocados[0:4]}")
print("-="*20)
print(f"entre os dez os 5 ultimos colocados são {colocados[-4:]}")
print("-="*20)
print(f"Os times em ordem alfabética é {sorted(colocados)}")
print("-="*20)
print(f"O time Fluminense está em {colocados.index('Fluminense')+1}")
print("-="*20)
